---

###
### Runs tests on master branch
###

name: "master branch"
on:
  schedule:
   - cron: "0 4 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Terraform test"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: "make test"
        run: |
          make test ARGS="-var allowed_account_id=${TF_VAR_allowed_account_id} -var role_to_assume=${TF_VAR_role_to_assume} -var transit_gateway_satellite_account_id=${TF_VAR_satellite_account_id}"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_allowed_account_id: ${{ secrets.AWS_ACCOUNT_ID_HUB }}
          TF_VAR_role_to_assume: ${{ secrets.ROLE_TO_ASSUME }}
          TF_VAR_satellite_account_id: ${{ secrets.AWS_ACCOUNT_ID_SATELLITE }}
